### ISSUE TITLE
What I've done wrong or why it will not work?

### ISSUE THREAD

**Issue by Filler1971** [wuub/rxv#10]
Hi, 
I've seen your python-project for yamaha rx-v xx3-series for better web control.
But I don't know how to use it.

What I've done:
I've installed python 2.7 on my Win8.1 and then copied your script in Scipt-Folder of Python.
After that I got on command-line "pip install rxv" and message said everythings fine.

Then I looked on my network for my RX-V573 (latest firmware 1.16). Fine, it's there.

After I clicked on it, web browser (latest firefox) opens and I see the same behaviour on web browser as before installing the script. Only settings for IP-Address and update firmware :(

Is there something wrong what I've done or still forgot an step to make?

It would be great if you could help me to get the more interesting web browser control for my RX-V573.

Thx forward

**Comment by wuub** [comment]
@Filler1971 unfortuneately I don't fully understand what you're trying to achieve, . rxv is a python library that in itself does not provide any web interface for Yamaha receivers, it can be used to create one with Python programming language, but nothing more.

Sorry :(
