### ISSUE TITLE
Volume setter fails when passed a value not ending with .0 or .5

### ISSUE THREAD

**Issue by Kernald** [wuub/rxv#35]
For some receivers if not all, volumes steps are 0.5dB: you can set -45dB, -45.5dB, but not -45.4dB. However, you *can* call the volume setter with arbitrary values like -45.4. It ends up in a failure and volume not being set:
```
17-01-07 18:19:42 ERROR (Thread-8) [rxv] Request <YAMAHA_AV cmd="PUT"><Main_Zone><Volume><Lvl><Val>-449</Val><Exp>1</Exp><Unit>dB</Unit></Lvl></Volume></Main_Zone></YAMAHA_AV> failed with b'<YAMAHA_AV rsp="PUT" RC="3"><Main_Zone><Volume><Lvl></Lvl></Volume></Main_Zone></YAMAHA_AV>'
```

I guess the [volume setter](https://github.com/wuub/rxv/blob/master/rxv/rxv.py#L422) should ensure the computed value is a multiple of 5, or take the closest multiple of five value.

I encountered this issue while using the yamaha component from home-assistant: home-assistant/home-assistant#5209

I'm not sure on the side on which this issue should be fixed, but I guess checking the input in rxv makes more sense. I can probably write a patch if that sounds like a good way to fix this issue.

**Comment by sdague** [comment]
What model is this an issue for?

**Comment by Kernald** [comment]
It occurs at least on a rx-v579. I don't have any other models to test on, but someone mentioned on the home-assistant issue that the newer rx-v581 was also impacted.

**Comment by wuub** [comment]
Fixed by @sdague
