### ISSUE TITLE
net_radio won't work if a station is already playing.

### ISSUE THREAD

**Issue by besi** [wuub/rxv#58]
When I attempt to change the radio station using the `net_radio` command, I can only set a station once, then it is stuck at that current station.
 
    >>> rx.net_radio('Bookmarks>_BesisBest>Radio Paradise')

**OK**: Radio Paradise is playing.

    >>> rx.net_radio('Bookmarks>Italia>Radio Italian Music')

**Problem**: The station does not change.

When I press the Left button on the physical remote all the way back to "Bookmarks" and then attempt to call net_radio then it will work fine.

So I guess the menu has to be reset to the root node before the station can be changed again.

I tried rx.menu_left() but this won't work, neither does menu_right(). `up` and `down` work fine:

```
>>> rx.menu_left()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/rxv/rxv.py", line 504, in menu_left
    return self._menu_cursor("Left")
  File "/Library/Python/2.7/site-packages/rxv/rxv.py", line 495, in _menu_cursor
    return self._request('PUT', request_text, zone_cmd=False)
  File "/Library/Python/2.7/site-packages/rxv/rxv.py", line 143, in _request
    raise ResponseException(res.content)
rxv.exceptions.ResponseException: <YAMAHA_AV rsp="PUT" RC="3"><NET_RADIO><List_Control><Cursor></Cursor></List_Control></NET_RADIO></YAMAHA_AV>
>>> rx.menu_down()
<Element 'YAMAHA_AV' at 0x1056a2ad0>
```

**Comment by besi** [comment]
`menu_left()` is not the same as `menu_return()` even though the left key works on my physical remote.

So when I go back in the menu structure manually I can achieve the desired result:

    rx.net_radio('Bookmarks>_BesisBest>Radio Paradise')
    rx.menu_return()
    rx.menu_return()
    rx.menu_return()
    rx.net_radio('Bookmarks>Italia>Radio Italian Music')

I would suggest that the `net_radio` comand makes sure, that the menu is reset before a new station is loaded.

**Comment by wuub** [comment]
> I would suggest that the net_radio makes sure, that the menu is reset before a new station is loaded.

I just did some tests using mitmproxy and the official app.
The official app does not seem to provide any way to reset the stateful position inside the net radio tree.

However:
```
<YAMAHA_AV rsp="GET" RC="0">
  <NET_RADIO>
    <List_Info>
      <Menu_Status>Ready</Menu_Status>
      <Menu_Layer>2</Menu_Layer>
      <Menu_Name>Locations</Menu_Name>
```
Menu_Layer looks promising. We could try to parse it out and reset menu position.

**Comment by wuub** [comment]
<Menu_Layer>1</Menu_Layer> is the top one BTW :)
