### ISSUE TITLE
HDMI inputs report False to Playback supported but they actually can over CEC

### ISSUE THREAD

**Issue by cloom** [wuub/rxv#62]
Hello,

I am using HomeAssistant which is using this library for Yamaha Media Players but I cannot use the media buttons as the library reports the HMDI input as "is_playback_supported" is returning False.

"is_playback_supported" is checking the "desc.xml" from the Receiver but none of the HDMI sources will show up in this file, even if they have a CEC enabled device connected to it.

Could this function assume HDMI devices are CEC enabled and just send the play/pause/stop/previous/next keys by default? The "desc.xml" file is static and I have not found a way to check if an HDMI source is CEC enabled or not so forcing it is the only way to make it work in Home Assistant.

Thank you.

**Comment by Twanislas** [comment]
Hi !
I'd like to see this happen as well, thanks !

**Comment by esev** [comment]
I encountered the same issue. It impacts the menu cursor keys too. Would anyone be able to test #69? For HA (docker), I've been testing by directly modifying the python package (`/usr/local/lib/python3.8/site-packages/rxv/rxv.py`).

With #69 & https://github.com/home-assistant/core/pull/44819, I was able to add a HA card and successfully control the HDMI devices.
![Screenshot 2021-01-05 at 9 24 25 AM](https://user-images.githubusercontent.com/289218/103678092-fa88d880-4f37-11eb-9183-38a86d9aed07.png)

**Comment by cloom** [comment]
Hello Eric,

Big thanks for looking into this and I love the idea of having a remote! I have to admit I am not sure how to push your commit into HA to test.

I believe we need to:
- get this great rxv library updated as HA depends on it,
- then request HA to use the new library
- and only then a request can be made to modify a component in HA.

Nevertheless, if that worked in HA the "dirty" way I don't see any reason not working once updated properly.

This code has not been touched for almost 2 years, @wuub would you be willing to accept @esev 's commit once reviewed?
I guess that's what we need before going any further.
